### PR TITLE
Added table of contents for easier navigation

### PR DESCRIPTION
**Pull request by MohanSha**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | NO 
| Patch: Bug Fix?          | No
| Minor: New Feature?      | No
| Major: Breaking Change?  | No
| Tests Added + Pass?      | Yes
| Documentation Provided   | Yes (code comments and or markdown)
| Any Dependency Changes?  | No
| License                  | Apache License, Version 2.0

### CODE REVIEW

**Comment by habansal** [comment]
@MohanSha Is there an issue backed by this PR ?
Currently, it mentions `Fixes #1, Fixes #2`

**Comment by habansal** [comment]
I changed Fixed Issues to NO and approving the PR :)

**Review by habansal — APPROVED** [review]

**Comment by habansal** [comment]
Also, changed the base branch from `master` to `development`.
@MohanSha Can you resolve the conflicts and I will merge this PR.
cc @samuelmeuli

**Comment by samuelmeuli** [comment]
This archetype has been merged into the [aem-project-archetype](https://github.com/adobe/aem-project-archetype), so the README has been replaced as well.

**Pull request closed without merging**
